// <auto-generated />
namespace IJSE.ARM.DataAccess.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(person));
        
        string IMigrationMetadata.Id
        {
            get { return "201706131839391_person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
